const mongoose = require('mongoose');

const journalLineSchema = new mongoose.Schema({
  account: { type: mongoose.Schema.Types.ObjectId, ref: 'Account', required: true },
  accountName: { type: String },
  debit: { type: Number, default: 0 },
  credit: { type: Number, default: 0 },
  narration: { type: String, trim: true },
});

const journalEntrySchema = new mongoose.Schema({
  entryNumber: { type: String, required: true, unique: true },
  date: { type: Date, required: true, default: Date.now },
  lines: { type: [journalLineSchema], validate: v => v.length >= 2 },
  narration: { type: String, trim: true },
  reference: { type: String, trim: true }, // link to invoice/order
  referenceType: { type: String, enum: ['invoice', 'order', 'expense', 'payment', 'manual', null] },
  referenceId: { type: mongoose.Schema.Types.ObjectId },
  isAutoGenerated: { type: Boolean, default: false },
  company: { type: mongoose.Schema.Types.ObjectId, ref: 'Company' },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
}, { timestamps: true });

journalEntrySchema.index({ date: -1 });
journalEntrySchema.index({ entryNumber: 1 });

module.exports = mongoose.model('JournalEntry', journalEntrySchema);
